#!/bin/bash

# Συνάρτηση ελέγχου Youtube Url
function url_check {
    if [[ $url = 'https://www.youtube.com/watch?'*v=* ]] || [[ $url == 'https://youtube.com/watch?'*v=* ]] || [[ $url == 'https://youtu.be'*/* ]] || [[ $url == 'm.youtube.com'** ]] || [[ $url == 'https://music.youtube.com/watch?'*v=* ]]
        then
            home="/home/""$USER""/Music"
            if [[ -d "$home" ]]; then
                cd "$home" || return
            else
                mkdir -p "$home"
                cd "$home" || return
            fi
            echo "########    Ytd101    ########"
            echo "# The download just started! #"
            
    else
            echo "This is not a Youtube Url." 
            exit
    fi
}
# Συνάρτηση μετατροπής σε mp3
function mp3 {
	youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 --output "%(title)s.%(ext)s" "$url"
}

# Συνάρτηση μετατροπής σε mp4
function mp4 {
    youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' "$url"
}

# Έλεγχος αν ο χρήστης πρόσθεσε δεύτερο όρισμα
function check_flag {
    if [[ "$url" != "" ]]; then
        url_check
    else
        echo "Add Url."
        exit 0
    fi
}

# Βασικό scipt με flags

if [[ "$#" == "0" ]];
then
    echo "No parameter given."
    echo "Run ytd --help to see the available options."
    exit 0
else
    if [[ $1 == "--help" ]];
        then 
            echo "--------------    Ytd101    ---------------"
            echo "               Script Format               "
            echo "             ytd --options url             "
            echo "             Available Options             "
            echo "        mp3: Convert the url to mp3        "
            echo "        mp4: Convert the url to mp4        "
            echo "-------------------------------------------"
    elif [[ $1 == "--mp3" ]]; then
            if [[ "$2" == "" ]]; then
                echo "-----------------------"
                echo "   Add url!   "
                echo "    ./ytd --mp3 url    "
            else    
                url="$2"
                check_flag url
                mp3 url
            fi
    elif [[ $1 == "--mp4" ]]; then
            if [[ "$2" == "" ]]; then
                echo "-----------------------"
                echo "   Add url!   "
                echo "    ./ytd --mp4 url    "
            else    
                url="$2"
                check_flag url
                mp4 url
            fi 
    else
        echo "--------------- Ytd ----------------"
        echo " Give one of the available options! "
        echo "             ytd --help             "
    fi
    
    
    
fi    

exit 0
